2023-09-14 13:29:38,613 - Server initialized for eventlet.
2023-09-14 13:29:38,614 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:29:38,955 - Use pytorch device: cpu
2023-09-14 13:30:57,861 - Server initialized for eventlet.
2023-09-14 13:30:57,862 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:30:58,109 - Use pytorch device: cpu
2023-09-14 13:31:21,261 - Server initialized for eventlet.
2023-09-14 13:31:21,262 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:31:21,480 - Use pytorch device: cpu
2023-09-14 13:38:49,265 - Server initialized for eventlet.
2023-09-14 13:38:49,265 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:38:49,552 - Use pytorch device: cpu
2023-09-14 13:40:22,256 - Server initialized for eventlet.
2023-09-14 13:40:22,257 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:40:22,525 - Use pytorch device: cpu
2023-09-14 13:40:29,034 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:40:30,976 - User sent message: hi
2023-09-14 13:40:30,976 - Bot response: Hello! How can I assist you today? Are you looking for information or need help with something specific?
<p style="color: red;">found user info: "Name","Link""Latest Appearance","The Legend of Zelda: Breath of the Wild (2017 as of my last update)""Main Shield","Hylian Shield"</p>

2023-09-14 13:40:33,939 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:40:38,938 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:40:43,915 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:40:48,991 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:40:54,010 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:40:58,924 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:03,916 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:08,959 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:13,976 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:18,997 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:24,012 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:28,928 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:33,916 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:38,917 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:43,918 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:48,997 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:41:54,656 - Server initialized for eventlet.
2023-09-14 13:41:54,657 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:41:54,944 - Use pytorch device: cpu
2023-09-14 13:41:58,935 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:03,949 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:08,966 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:13,983 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:19,001 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:24,019 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:29,037 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:33,951 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:38,971 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:43,989 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:48,917 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:42:54,424 - Server initialized for eventlet.
2023-09-14 13:42:54,425 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:42:54,722 - Use pytorch device: cpu
2023-09-14 13:42:59,177 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:43:03,955 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:44:03,009 - Server initialized for eventlet.
2023-09-14 13:44:03,010 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:44:03,283 - Use pytorch device: cpu
2023-09-14 13:44:03,968 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:44:08,981 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 13:47:45,892 - NumExpr defaulting to 8 threads.
2023-09-14 13:47:46,172 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:47:46,465 - Use pytorch device: cpu
2023-09-14 13:55:12,227 - NumExpr defaulting to 8 threads.
2023-09-14 13:55:12,503 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:55:12,794 - Use pytorch device: cpu
2023-09-14 13:57:57,842 - NumExpr defaulting to 8 threads.
2023-09-14 13:57:58,062 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 13:57:58,337 - Use pytorch device: cpu
2023-09-14 14:08:16,096 - NumExpr defaulting to 8 threads.
2023-09-14 14:08:16,335 - Server initialized for eventlet.
2023-09-14 14:08:16,336 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 14:08:16,619 - Use pytorch device: cpu
2023-09-14 14:08:28,038 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:09:06,017 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:09:08,478 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:09:08,909 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:11:52,711 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:11:53,105 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:12:15,045 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:12:16,900 - Exception on /api/image [POST]
Traceback (most recent call last):
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dako22/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/app.py", line 157, in upload_image
    image_info = mec.analyze_image_api(filename)
  File "/Users/dako22/Documents/GitHub/sheikah-tower/wrapper.py", line 43, in analyze_image_api
    print("Score: %.4f" % (sim_score))
TypeError: must be real number, not NoneType
2023-09-14 14:19:43,811 - NumExpr defaulting to 8 threads.
2023-09-14 14:19:44,026 - Server initialized for eventlet.
2023-09-14 14:19:44,027 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 14:19:44,303 - Use pytorch device: cpu
2023-09-14 14:20:47,362 - NumExpr defaulting to 8 threads.
2023-09-14 14:20:47,535 - Server initialized for eventlet.
2023-09-14 14:20:47,535 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-09-14 14:20:47,794 - Use pytorch device: cpu
2023-09-14 15:00:34,279 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
2023-09-14 15:00:39,485 - Error in location_api: MECApp.loc_user_api() takes 1 positional argument but 2 were given
